blueprint:
  name: Timer Notification
  description: שולח התראה כאשר טיימר מסתיים
  domain: automation
  input:
    timer_entity:
      name: Timer Entity
      description: בחר את הטיימר למעקב
      selector:
        entity:
          domain: timer
    notify_service:
      name: Notify Service
      description: השירות שישלח את ההתראה
      default: "notify.raz_telegram"
      selector:
        text:
trigger:
  platform: event
  event_type: timer.finished
  event_data:
    entity_id: !input timer_entity

action:
  - service: !input notify_service
    data:
      message: "⏳ הטיימר '{{ trigger.event.data.entity_id }}' הסתיים!"
      title: "⏰ התראה על טיימר"

mode: parallel
max: 5
