blueprint:
  name: Timer Notification with Custom Message
  description: שולח התראה כאשר טיימר מסתיים, עם הודעה מותאמת אישית
  domain: automation
  input:
    timer_entity:
      name: Timer Entity
      description: בחר את הטיימר למעקב
      selector:
        entity:
          domain: timer
    notify_service:
      name: Notify Service
      description: השירות שישלח את ההתראה
      default: "notify.raz_telegram"
      selector:
        text:
    custom_message:
      name: Custom Message
      description: ההודעה שתישלח כאשר הטיימר מסתיים (ניתן להשתמש ב-{{ timer }} כדי להכניס את שם הטיימר)
      default: "⏳ הטיימר '{{ timer }}' הסתיים!"
      selector:
        text:

trigger:
  platform: event
  event_type: timer.finished
  event_data:
    entity_id: !input timer_entity

action:
  - variables:
      timer: "{{ trigger.event.data.entity_id }}"
  - service: !input notify_service
    data:
      message: "{{ !input custom_message | replace('{{ timer }}', timer) }}"
      title: "⏰ התראה על טיימר"

mode: parallel
max: 5
