blueprint:
  name: "⏳ התראה בסיום טיימר"
  description: "שליחת התראה כאשר אחד מהטיימרים שבחרת מסתיים, עם אפשרות לפעולות."
  domain: automation
  input:
    timers:
      name: "בחירת טיימרים"
      description: "בחר טיימרים שעבורם תישלח התראה כאשר הם מסתיימים."
      selector:
        entity:
          domain: timer
          multiple: true

    notify_targets:
      name: "שירותי התראה"
      description: "בחר את שירותי ההתראה (כגון notify.mobile_app_xxx, notify.telegram)."
      selector:
        entity:
          domain: notify
          multiple: true

    notify_title:
      name: "כותרת ההודעה"
      description: "הזן כותרת מותאמת להודעה שתישלח כאשר טיימר יסתיים."
      selector:
        text:

    notify_message:
      name: "תוכן ההודעה"
      description: "הזן הודעה מותאמת שתישלח כאשר טיימר מסתיים. ניתן להשתמש ב-{{ timer }} עבור שם הטיימר."
      selector:
        text:

    notify_actions:
      name: "פעולות נוספות"
      description: "בחר אם להוסיף כפתורים להתראה (לדוגמה: השתקה, הפעלה מחדש)."
      default: []
      selector:
        object:

mode: parallel

trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: !input timers

action:
  - variables:
      timer: "{{ trigger.event.data.entity_id.split('.')[-1] }}"

  - repeat:
      for_each: !input notify_targets
      sequence:
        - service: "notify.{{ repeat.item.split('.')[-1] }}"
          data:
            title: !input notify_title
            message: "{{ notify_message | replace('{{ timer }}', timer) }}"
            data:
              actions: !input notify_actions
