blueprint:
  name: התראת צבע אדום לפי מיקום אנשים
  description: |
    שליחת התראות צבע אדום לפי המיקום הנוכחי של אנשים, כולל שליטה בעוצמת שמע,
    טלפון, TTS, אורות וטלוויזיה. מבוסס על סוג ההתרעה (מוקדמת, מיידית, סיום).
  domain: automation
  input:
    people:
      name: אנשים ומיקומים
      description: רשימת אנשים עם טלפון וחיישן מיקום
      selector:
        object:
          multiple: true
    presence_entities:
      name: ישויות לזיהוי נוכחות בבית
      description: "לדוגמה: טלפון, beacon, חיישן BLE."
      default: []
      selector:
        entity:
          multiple: true
    evening_lights:
      name: אורות להדלקה בלילה
      selector:
        entity:
          domain: light
          multiple: true
    all_day_lights:
      name: אורות להדלקה כל היום
      selector:
        entity:
          domain: light
          multiple: true
    custom_actions_early:
      name: פעולות נוספות - מוקדמת
      default: []
      selector:
        action:
    custom_actions_immediate:
      name: פעולות נוספות - מיידית
      default: []
      selector:
        action:
    custom_actions_clear:
      name: פעולות נוספות - סיום התרעה
      default: []
      selector:
        action:

# שאר הקוד נשאר ללא שינוי
