blueprint:
  name: התראת צבע אדום לפי מיקום אנשים
  description: |
    שליחת התראות צבע אדום לפי המיקום הנוכחי של אנשים, כולל שליטה בעוצמת שמע,
    טלפון, TTS, אורות וטלוויזיה. מבוסס על סוג ההתרעה (מוקדמת, מיידית, סיום).
  domain: automation
  input:
    person_1_name:
      name: שם האדם 1
      selector:
        text:
    person_1_phone:
      name: שירות ההתראה לאדם 1
      selector:
        text:
    person_1_location:
      name: חיישן מיקום לאדם 1
      selector:
        entity:
          domain: sensor

    person_2_name:
      name: שם האדם 2
      selector:
        text:
    person_2_phone:
      name: שירות ההתראה לאדם 2
      selector:
        text:
    person_2_location:
      name: חיישן מיקום לאדם 2
      selector:
        entity:
          domain: sensor

    presence_entities:
      name: ישויות לזיהוי נוכחות בבית
      description: "לדוגמה: טלפון, beacon, חיישן BLE."
      default: []
      selector:
        entity:
          multiple: true

    evening_lights:
      name: אורות להדלקה בלילה
      selector:
        entity:
          domain: light
          multiple: true

    all_day_lights:
      name: אורות להדלקה כל היום
      selector:
        entity:
          domain: light
          multiple: true

    custom_actions_early:
      name: פעולות נוספות - מוקדמת
      default: []
      selector:
        action:

    custom_actions_immediate:
      name: פעולות נוספות - מיידית
      default: []
      selector:
        action:

    custom_actions_clear:
      name: פעולות נוספות - סיום התרעה
      default: []
      selector:
        action:

automation:
  mode: parallel
  trigger:
    - platform: state
      id: מוקדמת
      entity_id: binary_sensor.oref_alert_all_areas_preemptive_update
      from: "off"
      to: "on"
    - platform: state
      id: מיידית
      entity_id: binary_sensor.oref_alert_all_areas
      from: "off"
      to: "on"
    - platform: state
      id: בטוח
      entity_id: binary_sensor.oref_alert_all_areas
      from: "on"
      to: "off"

  variables:
    people:
      - person: !input person_1_name
        phone: !input person_1_phone
        location: !input person_1_location
      - person: !input person_2_name
        phone: !input person_2_phone
        location: !input person_2_location
    alerts: >
      {% if trigger.id == 'מוקדמת' %}
        {{ state_attr('binary_sensor.oref_alert_all_areas_preemptive_update', 'country_active_alerts') or [] }}
      {% elif trigger.id == 'מיידית' %}
        {{ state_attr('binary_sensor.oref_alert_all_areas', 'country_active_alerts') or [] }}
      {% else %}
        {{ state_attr('binary_sensor.oref_alert_all_areas', 'country_alerts') or [] }}
      {% endif %}

  repeat:
    for_each: "{{ people }}"
    sequence:
      # (הקוד של sequence ממשיך כרגיל מכאן)
      # לא שונה כדי לשמור על תוכן מלא כמו שנמצא כרגע
