blueprint:
  name: התראת צבע אדום לפי מיקום אנשים
  description: |
    שליחת התראות צבע אדום לפי המיקום הנוכחי של אנשים, כולל שליטה בעוצמת שמע,
    טלפון, TTS, אורות וטלוויזיה. מבוסס על סוג ההתרעה (מוקדמת, מיידית, סיום).
  domain: automation
  input:
    person_1_name:
      name: שם האדם 1
      selector:
        text:

    person_1_phone:
      name: שירות ההתראה (notify) לאדם 1
      selector:
        text:

    person_1_location:
      name: חיישן מיקום לאדם 1
      selector:
        entity:
          domain: sensor

    person_2_name:
      name: שם האדם 2
      selector:
        text:

    person_2_phone:
      name: שירות ההתראה (notify) לאדם 2
      selector:
        text:

    person_2_location:
      name: חיישן מיקום לאדם 2
      selector:
        entity:
          domain: sensor

    presence_entities:
      name: ישויות לזיהוי נוכחות בבית
      description: "לדוגמה: טלפון, beacon, חיישן BLE."
      default: []
      selector:
        entity:
          multiple: true

    evening_lights:
      name: אורות להדלקה בלילה
      selector:
        entity:
          domain: light
          multiple: true

    all_day_lights:
      name: אורות להדלקה כל היום
      selector:
        entity:
          domain: light
          multiple: true

    custom_actions_early:
      name: פעולות נוספות - מוקדמת
      default: []
      selector:
        action:

    custom_actions_immediate:
      name: פעולות נוספות - מיידית
      default: []
      selector:
        action:

    custom_actions_clear:
      name: פעולות נוספות - סיום התרעה
      default: []
      selector:
        action:

automation:
  mode: parallel
  trigger:
    - platform: state
      id: מוקדמת
      entity_id: binary_sensor.oref_alert_all_areas_preemptive_update
      from: "off"
      to: "on"
    - platform: state
      id: מיידית
      entity_id: binary_sensor.oref_alert_all_areas
      from: "off"
      to: "on"
    - platform: state
      id: בטוח
      entity_id: binary_sensor.oref_alert_all_areas
      from: "on"
      to: "off"

  variables:
    people:
      - person: !input person_1_name
        phone: !input person_1_phone
        location: !input person_1_location
      - person: !input person_2_name
        phone: !input person_2_phone
        location: !input person_2_location

    alerts: >
      {% if trigger.id == 'מוקדמת' %}
        {{ state_attr('binary_sensor.oref_alert_all_areas_preemptive_update', 'country_active_alerts') or [] }}
      {% elif trigger.id == 'מיידית' %}
        {{ state_attr('binary_sensor.oref_alert_all_areas', 'country_active_alerts') or [] }}
      {% else %}
        {{ state_attr('binary_sensor.oref_alert_all_areas', 'country_alerts') or [] }}
      {% endif %}

  repeat:
    for_each: "{{ people }}"
    sequence:
      - variables:
    city: "{{ state_attr(repeat.item.location, 'city') }}"
    postal_town: "{{ state_attr(repeat.item.location, 'postal_town') }}"
    alert_areas: "{{ alerts | map(attribute='data') | list }}"
    previous_alerts: "{{ state_attr('binary_sensor.oref_alert_all_areas', 'country_alerts') or [] }}"
    previous_area_names: "{{ previous_alerts | map(attribute='data') | list }}"
    was_alerted: "{{ city in previous_area_names or postal_town in previous_area_names }}"
    matched_area: >
      {% if postal_town in alert_areas %}{{ postal_town }}{% else %}{{ city }}{% endif %}
    message_text_early: "לפי נתוני פיקוד העורף - החות'ים ככל הנראה שיגרו טילים לאזור {{ matched_area }}. זו התרעה מוקדמת."
    message_text_immediate: "טיל מתקרב לאזור {{ matched_area }}. יש להיכנס מיידית למרחב מוגן."
    message_text_clear: "האיום הוסר באזור {{ matched_area }}. ניתן לצאת מהמרחב המוגן."

- condition: template
  value_template: "{{ city in alert_areas or postal_town in alert_areas or (trigger.id == 'בטוח' and was_alerted) }}"

- choose:
    - conditions:
        - condition: trigger
          id: מוקדמת
      sequence:
        - service: "{{ repeat.item.phone }}"
          data:
            message: command_volume_level
            data:
              media_stream: alarm_stream
              command: 15
              ttl: 0
              priority: high
        - service: "{{ repeat.item.phone }}"
          data:
            title: התראה מוקדמת - צבע אדום
            message: "{{ message_text_early }}"
            data:
              ttl: 0
              priority: high
        - service: "{{ repeat.item.phone }}"
          data:
            message: TTS
            data:
              tts_text: "{{ message_text_early }}"
              media_stream: alarm_stream
              ttl: 0
              priority: high
        - choose:
            - conditions:
                - condition: or
                  conditions:
                    - condition: state
                      entity_id: !input presence_entities
                      state: home
          sequence:
            - choose:
                - conditions:
                    - condition: time
                      after: '19:30:00'
                      before: '07:00:00'
                  sequence:
                    - service: light.turn_on
                      target:
                        entity_id: !input evening_lights
                - conditions: []
                  sequence:
                    - service: light.turn_on
                      target:
                        entity_id: !input all_day_lights
        - service: media_player.volume_mute
          data:
            is_volume_muted: true
          target:
            device_id: 7ed0cf10aa9f0ec9775c4ac31712315d
        - choose: []
          default: !input custom_actions_early

    - conditions:
        - condition: trigger
          id: מיידית
      sequence:
        - service: "{{ repeat.item.phone }}"
          data:
            title: התראה מיידית - צבע אדום
            message: "{{ message_text_immediate }}"
            data:
              ttl: 0
              priority: high
        - service: "{{ repeat.item.phone }}"
          data:
            message: TTS
            data:
              tts_text: "{{ message_text_immediate }}"
              media_stream: alarm_stream
              ttl: 0
              priority: high
        - service: media_player.volume_mute
          data:
            is_volume_muted: true
          target:
            device_id: 7ed0cf10aa9f0ec9775c4ac31712315d
        - choose: []
          default: !input custom_actions_immediate

    - conditions:
        - condition: trigger
          id: בטוח
      sequence:
        - service: "{{ repeat.item.phone }}"
          data:
            title: סיום התרעה - בטוח
            message: "{{ message_text_clear }}"
            data:
              ttl: 0
              priority: high
        - service: "{{ repeat.item.phone }}"
          data:
            message: TTS
            data:
              tts_text: "{{ message_text_clear }}"
              media_stream: alarm_stream
              ttl: 0
              priority: high
        - service: media_player.volume_mute
          data:
            is_volume_muted: false
          target:
            device_id: 7ed0cf10aa9f0ec9775c4ac31712315d
        - choose: []
          default: !input custom_actions_clear
