blueprint:
  name: "转专 Ai 拽 "
  description: "Blueprint 转专转 AI 注转 拽转  专."
  domain: automation
  input:
    switch_entity:
      name: "转 拽转 "
      selector:
        entity:
          domain: switch
    timer_entity:
      name: "专 "
      selector:
        entity:
          domain: timer
    notify_target:
      name: "注 转专"
      selector:
        entity:
          domain: notify
    computer_notify_target:
      name: "转专 砖"
      selector:
        entity:
          domain: notify
    shield_notify_target:
      name: "转专 Nvidia Shield"
      selector:
        entity:
          domain: notify

automation:
  - alias:  拽  拽
    trigger:
      - platform: state
        entity_id: !input switch_entity
        to: "on"
    action:
      - alias: 砖  TTS 转 拽 专
        service: notify.mobile_app_raz_phone
        data:
          message: command_volume_level
          data:
            media_stream: alarm_stream
            command: >-
              {{ 6 if is_state('device_tracker.raz_bermuda_tracker_bermuda_tracker', 'home') else 15 }}
            ttl: 0
            priority: high
      - variables:
          person_name: |-
            {% if now().hour < 3 %}
              "  住"
            {% elif now().hour < 5 %}
              "驻转 拽专  住"
            {% elif now().hour < 12 %}
              "拽专  住"
            {% elif now().hour < 16 %}
              "爪专  住"
            {% elif now().hour < 19 %}
              "专 爪专  住"
            {% elif now().hour < 22 %}
              "注专  住"
            {% else %}
              "  住"
            {% endif %}
          finish_time: >-
            {% set remaining_time = state_attr(!input timer_entity, 'remaining') %} 
            {% if remaining_time %}
              {% set remaining_parts = remaining_time.split(':') %}
              {% set minutes = remaining_parts[1] | int %}
              {% set seconds = remaining_parts[2] | int %}
              {% set now = now() %}
              {% set finish_time = now + timedelta(minutes=minutes, seconds=seconds) %}
              {{ finish_time.strftime('%H:%M') }}
            {% else %}
              " 注"
            {% endif %}
          ai_prompt: >-
             转注   转. 专拽 转专砖  住拽专 注专转 砖注转: {{ person_name }},
            {% if states(!input switch_entity) == 'on' %}
                 砖注: {{ finish_time }}.
               砖转专 住: {{ state_attr(!input timer_entity, 'remaining') }}.
            {% else %}
               .
            {% endif %}
      - service: conversation.process
        data:
          agent_id: conversation.google_generative_ai
          text: "{{ ai_prompt }}"
          language: he
        response_variable: shisha
      - variables:
          tts_message: >-
            {% if shisha.response.speech.plain.speech is defined and shisha.response.speech.plain.speech | string | trim != '' %}
              {{ shisha.response.speech.plain.speech | string }}
            {% else %}
               ! 驻砖专 转 注砖 
            {% endif %}
          notify_title: " 注   砖 专! "
      - parallel:
          - service: !input notify_target
            data:
              message: "{{ tts_message }}"
              title: "{{ notify_title }}"
              data:
                ttl: 0
                priority: high
                importance: high
                sticky: true
                visibility: public
          - service: !input notify_target
            data:
              message: TTS
              data:
                media_stream: alarm_stream
                ttl: 0
                priority: high
                importance: high
                tts_lang: heb
                tts_text: "{{ tts_message }}"
                visibility: public
          - service: !input computer_notify_target
            data:
              message: "{{ tts_message }}"
          - service: !input shield_notify_target
            data:
              title: "转专转 转:"
              message: "{{ tts_message }}"
              data:
                icon:
                  path: /config/www/pictures/logo.png
                fontsize: large
                position: top-right
                duration: 15
                transparency: 50%
                interrupt: 1
                ttl: 0
                priority: high
                importance: high
                sticky: true
                visibility: public
